name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    # this event is submited via github.com/bots-house/github-actions-upstream-watch
    types: upstream_commit
  schedule:
    - cron: '0 1 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: Checkout upstream repo 
        uses: actions/checkout@v2
        with:
          repository: cloudflare/cloudflared
          path: upstream
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      - 
        name: Get Latest Tag Of Upstream Source Code
        id: download
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/wangyu-/udp2raw-tunnel/releases" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          echo ::set-output name=latest_tag::${VERSION}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udp2raw:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udp2raw:${{ steps.download.outputs.latest_tag }}
